version: '3.4'

services:
  userdb:
    container_name: userdb
    restart: always
    ports:
      - "6379:6379"

  crewdb:
    container_name: crewdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  pilotdb:
    container_name: pilotdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=PilotDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  flightdb:
    container_name: flightdb
    environment:
        SA_PASSWORD: "Razz12345"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1433:1433"

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@flightproject.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  authentication.api:
    container_name: authentication.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=userdb:6379"
    depends_on:
      - userdb
    ports:
      - "8000:80"

  crew.api:
    container_name: crew.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://crewdb:27017"
    depends_on:
      - crewdb
    ports:
      - "8001:80"

  pilot.api:
    container_name: pilot.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=pilotdb;Post=5432;Database=PilotDb;User Id=admin;Password=admin1234"
    depends_on:
      - pilotdb
    ports:
      - "8002:80"


  flight.api:
    container_name: flight.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:FlightConnectionString=Server=localhost;Database=FlightDb;User Id=sa;Password=Razz12345"
    depends_on:
      - flightdb
    ports:
      - "8003:80"


  ocelotgateway:
    container_name: ocelotgw
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - authentication.api
      - crew.api
      - pilot.api
      - flight.api
    ports:
      - "8010:80"

